#image: gitpod/workspace-full-vnc  -uncomment to use

ports:
  - port: 0-65000
    visibility: private
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: false

#additionalRepositories:
#  - url: DotfilesURL
#    checkoutLocation: .dotfiles
#  - url: ProjectURL
#    checkoutLocation: ProjectDir
    
workspaceLocation: "${GITPOD_REPO_ROOTS}/main.code-workspace"
